EnterTheMatrix/Models/Question.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EnterTheMatrix.Models
{
    public class Question
    {
        public int QuestionId { get; set; }
        public string Riddle { get; set; }
        public string Answer { get; set; }
        public string PossibleAnswerOne { get; set; }
        public string PossibleAnswerTwo { get; set; }
        public string PossibleAnswerThree { get; set; }
    }
}

EnterTheMatrix/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace EnterTheMatrix.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }


    }
}

EnterTheMatrix/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EnterTheMatrix.Services;

namespace EnterTheMatrix.Controllers
{
    public class QuestionController : Controller
    {
        private IQuestionRepository repository;

        public QuestionController(IQuestionRepository repo)
        {
            repository = repo;
        }

        public ViewResult List() => View(repository.Questions);

    }
}

EnterTheMatrix/Views/Home/Index.cshtml
<h3>Enter the Matrix</h3>
<form action="/" method="post">
    <p>
        <button class="btn btn-sm" asp-controller="Question" asp-action="List">enter</button>
        <button class="btn btn-sm">close</button>
    </p>



</form>

EnterTheMatrix/Views/Question/List.cshtml
@model IEnumerable<Question>

    @foreach (var q in Model)
    {
        <div>
            <h3>@q.Riddle</h3>
        </div>

        <div>
            <p>Answers:</p>
            <p>@q.PossibleAnswerOne</p>
            <p>@q.PossibleAnswerTwo</p>
            <p>@q.PossibleAnswerThree</p>
        </div>
    }

EnterTheMatrix/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>

    @RenderBody()

</body>
</html>